Repository prgrms-be-devcourse/NBE3-4-1-Team03, pull requests merged in 2025-01, with the labels that each got.

#28 [FEAT] : [FE] 회원 가입 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/InputField.jsx
  frontend/src/hooks/useApi.js
  frontend/src/hooks/useFetch.js
  frontend/src/hooks/useFormValidation.js
  frontend/src/pages/Signup.jsx
Labels: enhancement, frontend, layout

#26 [FEAT]: 회원가입 기능 구현 #24
  backend/src/main/java/com/app/backend/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/app/backend/domain/user/dto/request/UserInfoModifyRequest.java
  backend/src/main/java/com/app/backend/domain/user/dto/request/UserSignupRequest.java
  backend/src/main/java/com/app/backend/domain/user/dto/response/UserInfoResponse.java
  backend/src/main/java/com/app/backend/domain/user/entity/User.java
  backend/src/main/java/com/app/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/app/backend/domain/user/service/UserService.java
  backend/src/main/java/com/app/backend/global/aop/AppAspects.java
  backend/src/main/java/com/app/backend/global/config/AppConfig.java
  backend/src/main/java/com/app/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/app/backend/global/rs/RsData.java
  backend/src/main/java/com/app/backend/global/security/SecurityConfig.java
  backend/src/main/resources/config/application-dev_db.yml
  backend/src/test/java/com/app/backend/user/ApiV1UserControllerTest.java
Labels: enhancement

#25 feat 상품 전체 페이지 조회, 단일 상품 조회 구현 #20
  backend/src/main/java/com/app/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/app/backend/domain/product/dto/PageDto.java
  backend/src/main/java/com/app/backend/domain/product/dto/ProductDetailDto.java
  backend/src/main/java/com/app/backend/domain/product/dto/ProductPageDto.java
  backend/src/main/java/com/app/backend/domain/product/dto/ProductWithoutDescriptionDto.java
  backend/src/main/java/com/app/backend/domain/product/entity/Product.java
  backend/src/main/java/com/app/backend/domain/product/exception/ProductException.java
  backend/src/main/java/com/app/backend/domain/product/repository/ProductRepository.java
  backend/src/main/java/com/app/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/app/backend/global/config/AppConfig.java
  backend/src/main/java/com/app/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/app/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/com/app/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/app/backend/product/ProductControllerTest.java
  backend/src/test/java/com/app/backend/user/ApiV1UserControllerTest.java
Labels: enhancement

#33 [FEAT] 상품 검색 기능 추가 #31
  backend/src/main/java/com/app/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/app/backend/domain/product/repository/ProductRepository.java
  backend/src/main/java/com/app/backend/domain/product/service/ProductService.java
  backend/src/test/java/com/app/backend/product/ProductControllerTest.java
  backend/src/test/resources/config/application-test_db.yml
Labels: enhancement

#32 [FEAT] : [FE] 메인페이지 및 상품 조회 컴포넌트 구현
  frontend/src/App.jsx
  frontend/src/components/Error.jsx
  frontend/src/components/Loading.jsx
  frontend/src/components/ProductList.jsx
  frontend/src/components/ProductSearch.jsx
  frontend/src/context/ProductContext.jsx
  frontend/src/context/ProductReducer.js
  frontend/src/hooks/useFetch.js
  frontend/src/pages/Main.jsx
  frontend/src/utils.js
Labels: enhancement, frontend, layout

#35 [FEAT] : 회원 정보 조회 및 수정 #30
  backend/src/main/java/com/app/backend/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/app/backend/domain/user/dto/request/UserChangePasswordRequest.java
  backend/src/main/java/com/app/backend/domain/user/dto/response/UserInfoResponse.java
  backend/src/main/java/com/app/backend/domain/user/entity/User.java
  backend/src/main/java/com/app/backend/domain/user/entity/UserRole.java
  backend/src/main/java/com/app/backend/domain/user/entity/UserStatus.java
  backend/src/main/java/com/app/backend/domain/user/service/UserService.java
  backend/src/main/java/com/app/backend/global/config/AppConfig.java
  backend/src/main/java/com/app/backend/global/error/exception/ErrorCode.java
  backend/src/test/java/com/app/backend/user/ApiV1UserControllerTest.java
Labels: enhancement

#43 [FEAT] [BE] Product stock 관련 함수 구현 #42
  backend/src/main/java/com/app/backend/domain/product/service/ProductService.java
Labels: enhancement

#48 [FEAT] : [FE] 장바구니 담기 및 주문 생성 기능 구현
  frontend/src/App.jsx
  frontend/src/components/CartPage.jsx
  frontend/src/components/CartPayment.jsx
  frontend/src/components/Error.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/OkCancelModal.jsx
  frontend/src/components/ProductList.jsx
  frontend/src/context/CartContext.jsx
  frontend/src/context/CartReducer.js
  frontend/src/pages/Cart.jsx
  frontend/src/pages/Main.jsx
Labels: enhancement, frontend, layout

#46 feat: [BE] 회원 주문 목록 조회
  backend/src/main/java/com/app/backend/domain/user/controller/ApiV1UserController.java
  backend/src/test/java/com/app/backend/user/ApiV1UserControllerTest.java
Labels: enhancement

#47 [FEAT] [BE] : 로그인 및 로그아웃 기능 구현
  backend/.gitignore
  backend/README.md
  backend/build.gradle.kts
  backend/docker-compose.yml
  backend/src/main/java/com/app/backend/global/config/RedisConfig.java
  backend/src/main/java/com/app/backend/global/redis/repository/RedisRepository.java
  backend/src/main/java/com/app/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/app/backend/global/security/dto/LoginDto.java
  backend/src/main/java/com/app/backend/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/app/backend/global/security/filter/JwtAuthorizationFilter.java
  backend/src/main/java/com/app/backend/global/security/handler/JwtLogoutHandler.java
  backend/src/main/java/com/app/backend/global/security/handler/JwtLogoutSuccessHandler.java
  backend/src/main/java/com/app/backend/global/security/user/CustomUserDetails.java
  backend/src/main/java/com/app/backend/global/security/user/CustomUserDetailsService.java
  backend/src/main/java/com/app/backend/global/security/util/AuthResponseUtil.java
  backend/src/main/java/com/app/backend/global/security/util/JwtUtil.java
  backend/src/main/resources/config/application-dev_auth.yml
  backend/src/main/resources/config/application-dev_db.yml
  backend/src/test/java/com/app/backend/global/redis/config/TestRedisConfig.java
  backend/src/test/java/com/app/backend/global/security/util/JwtUtilTest.java
  backend/src/test/resources/config/application-test_auth.yml
  backend/src/test/resources/config/application-test_db.yml
Labels: enhancement

#56 [REFACTOR]: [BE] Security 권한 필터 추가 및 test 적용
  backend/src/main/java/com/app/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/app/backend/global/annotation/CustomWithMockAdmin.java
  backend/src/test/java/com/app/backend/global/config/CustomWithSecurityContextFactory.java
  backend/src/test/java/com/app/backend/product/ApiV1ProductControllerTest.java
  backend/src/test/java/com/app/backend/user/ApiV1UserControllerTest.java
Labels: enhancement, refactoring

#51 [FEAT]: [BE] 관리자 주문 조회 기능 추가 등
  backend/src/main/java/com/app/backend/domain/order/constant/OrderMessageConstant.java
  backend/src/main/java/com/app/backend/domain/order/controller/OrderController.java
  backend/src/main/java/com/app/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/app/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/app/backend/domain/user/controller/AdminController.java
  backend/src/main/java/com/app/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/com/app/backend/global/initdata/BaseInitData.java
  backend/src/test/java/com/app/backend/domain/order/controller/OrderControllerTest.java
  backend/src/test/java/com/app/backend/domain/order/repository/OrderRepositoryTest.java
  backend/src/test/java/com/app/backend/domain/order/service/OrderServiceTest.java
  backend/src/test/java/com/app/backend/domain/user/controller/AdminControllerTest.java
Labels: enhancement

#59 [FEAT] : [FE] 로그인 및 로그아웃 구현
  frontend/src/App.jsx
  frontend/src/components/CartPayment.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/OkCancelModal.jsx
  frontend/src/components/ProductDetailModal.jsx
  frontend/src/context/AuthContext.jsx
  frontend/src/hooks/useApi.js
  frontend/src/main.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/PrivateRoute.jsx
  frontend/src/pages/Signup.jsx
Labels: enhancement, frontend, layout

#55 [REFACTOR]: [BE] Product stock 관련 함수 개편
  .github/workflows/build_test.yml
  backend/src/main/java/com/app/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/app/backend/global/config/RedisConfig.java
  backend/src/main/java/com/app/backend/global/redis/listener/RedisKeyListener.java
  backend/src/main/java/com/app/backend/global/redis/repository/RedisRepository.java
  backend/src/main/java/com/app/backend/global/security/SecurityConfig.java
  backend/src/test/resources/config/application-test_db.yml
Labels: refactoring

#60 [FEAT] : [BE] 회원 인증 로직 추가
  backend/src/main/java/com/app/backend/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/app/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/com/app/backend/global/security/SecurityConfig.java
  backend/src/test/java/com/app/backend/user/ApiV1UserControllerTest.java
Labels: enhancement

#61 [FEAT] : [BE] Logout filter 예외처리 수정
  backend/src/main/java/com/app/backend/global/security/handler/JwtLogoutHandler.java
Labels: enhancement

#64 [FEAT] : [FE] 상품 등록 컴포넌트 추가
  frontend/src/App.jsx
  frontend/src/pages/Admin.jsx
  frontend/src/pages/NewProduct.jsx
  frontend/src/pages/NotFound404.jsx
  frontend/src/pages/Signup.jsx
Labels: enhancement, frontend, layout

#68 [FEAT]: [BE] 주문 관련 이메일 발송 기능 구현
  backend/build.gradle.kts
  backend/src/main/java/com/app/backend/BackendApplication.java
  backend/src/main/java/com/app/backend/domain/order/constant/OrderMessageConstant.java
  backend/src/main/java/com/app/backend/domain/order/dto/request/OrderProductRequest.java
  backend/src/main/java/com/app/backend/domain/order/dto/request/OrderRequest.java
  backend/src/main/java/com/app/backend/domain/order/dto/response/OrderProductResponse.java
  backend/src/main/java/com/app/backend/domain/order/dto/response/OrderResponse.java
  backend/src/main/java/com/app/backend/domain/order/repository/OrderProductRepository.java
  backend/src/main/java/com/app/backend/domain/order/repository/OrderProductRepositoryCustom.java
  backend/src/main/java/com/app/backend/domain/order/repository/OrderProductRepositoryImpl.java
  backend/src/main/java/com/app/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/app/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/app/backend/domain/order/util/OrderUtil.java
  backend/src/main/java/com/app/backend/domain/user/controller/AdminController.java
  backend/src/main/java/com/app/backend/global/constant/MailMessageConstant.java
  backend/src/main/java/com/app/backend/global/initdata/BaseInitData.java
  backend/src/main/java/com/app/backend/global/util/MailUtil.java
  backend/src/main/resources/config/application-dev_auth.yml
  backend/src/test/java/com/app/backend/domain/order/controller/OrderControllerTest.java
  backend/src/test/java/com/app/backend/domain/order/repository/OrderProductRepositoryTest.java
  backend/src/test/java/com/app/backend/domain/order/repository/OrderRepositoryTest.java
  backend/src/test/java/com/app/backend/domain/order/service/OrderServiceTest.java
  backend/src/test/java/com/app/backend/domain/user/controller/AdminControllerTest.java
  backend/src/test/java/com/app/backend/global/annotation/RepositoryTest.java
  backend/src/test/java/com/app/backend/global/config/TestMailConfig.java
  backend/src/test/java/com/app/backend/global/initdata/InitDummyData.java
  backend/src/test/java/com/app/backend/global/util/ReflectionUtil.java
  backend/src/test/resources/config/application-test_auth.yml
Labels: enhancement

#72 OrderServiceTest, ApiV1ProductControllerTest 수정
  backend/src/main/java/com/app/backend/domain/order/service/OrderService.java
  backend/src/test/java/com/app/backend/domain/order/service/OrderServiceTest.java
  backend/src/test/java/com/app/backend/product/ApiV1ProductControllerTest.java
Labels: refactoring

#74 [FIX]: [BE] 주문 생성 시간 기준 배송 상태 반영 수정
  backend/src/main/java/com/app/backend/domain/order/service/OrderService.java
  backend/src/test/java/com/app/backend/domain/order/service/OrderServiceTest.java
Labels: bug

#76 [FEAT]: [BE] 보안설정 추가 구현
  backend/src/main/java/com/app/backend/global/security/filter/JwtAuthorizationFilter.java
  backend/src/main/java/com/app/backend/global/security/handler/JwtLogoutHandler.java
  backend/src/main/java/com/app/backend/global/security/util/JwtUtil.java
Labels: enhancement

#82 [REFACTOR]: [BE] BaseInitData 수정
  backend/src/main/java/com/app/backend/domain/order/entity/Order.java
  backend/src/main/java/com/app/backend/global/initdata/BaseInitData.java
Labels: refactoring

#83 [FEAT]: [BE] Login valid 기능 추가
  backend/src/main/java/com/app/backend/global/security/dto/LoginDto.java
  backend/src/main/java/com/app/backend/global/security/filter/JwtAuthenticationFilter.java
Labels: enhancement

#85 [REFACTOR]: [BE] CORS Config 수정
  backend/src/main/java/com/app/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/app/backend/global/security/filter/JwtAuthorizationFilter.java
Labels: refactoring
